[global]
# 清华源（国内首选）
index-url = https://pypi.tuna.tsinghua.edu.cn/simple
timeout = 6000
# 开启缓存、并行下载加速
cache-dir = ~/.cache/pip
[install]
trusted-host = pypi.tuna.tsinghua.edu.cn
# 全局开启依赖并行安装
parallel-builds = 10
